#!/bin/bash

install() {
  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # prepare vars
  local name="ngrok"
  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./${name}"

  # prepare context
  cd $tmp_dir

  # reference: https://bin.equinox.io/c/bNyj1mQVY4c
  # example:
  #   https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
  #   https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.tgz
  # generate url
  local url="https://bin.equinox.io/c/bNyj1mQVY4c/${name}-${PACKAGE_CORE_VERSION}-${platform}-${arch}.tar.gz"
  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::download $tmp_file $url

  # extract
  tar -zxvf $tmp_file >>/dev/null 2>&1

  # install
  sudo mv $bin_file $usr_bin_dir/$name

  # clean
  rm -rf $tmp_dir
}

export -f install
